version: "{build}"

os: Visual Studio 2015

platform: 
  - x86

environment:
  MSVC_DEFAULT_OPTIONS: ON
  BOOST_ROOT: C:\Libraries\boost_1_59_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_59_0\lib32-msvc-14.0

init:
  - cmd: cmake --version
  - cmd: msbuild /version

clone_folder: C:\projects\testgit

branches:
  except:
    - gh-pages

before_build:
  - mkdir build

build_script:
  - cd build
 # $(appveyor_repo_tag_name)=VERSION
  - cmake -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" ..
  - cmake --build . 
  - mv Debug/main.exe ../
  - cmd: dir
  - cd ..
  - cmd: dir

test_script:
  - cmd: main.exe
  - cmd: main.exe -version

deploy:
  provider: Github
  auth_token:
    secure: 2ep5AcGb2Wl/vxhuoj8sYg/pTrcMmyChrOaS/BEytYqpPNB49lmkNVRrFpYB3KkL
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true

  
