version: "{build}"

os: Visual Studio 2015

platform: 
  - x64
  - Win32
  

environment:
  MSVC_DEFAULT_OPTIONS: ON
  BOOST_ROOT: C:\Libraries\boost_1_59_0
  BOOST_LIBRARYDIR_32: C:\Libraries\boost_1_59_0\lib32-msvc-14.0
  BOOST_LIBRARYDIR_64: C:\Libraries\boost_1_59_0\lib64-msvc-14.0

init:
  - cmd: cmake --version
  - cmd: msbuild /version

clone_folder: C:\projects\testgit

branches:
  except:
    - gh-pages

before_build:
  - mkdir build

build_script:
        # =VERSION
  - cd build
  - cmd: if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 14 2015
  - cmd: if "%platform%"=="x64" set CMAKE_GENERATOR_NAME=Visual Studio 14 2015 Win64
  - cmd: if "%platform%"=="Win32" set BOOST_LIBRARYDIR="%BOOST_LIBRARYDIR_32%"
  - cmd: if "%platform%"=="x64" set BOOST_LIBRARYDIR="%BOOST_LIBRARYDIR_64%"
  - cmd: if "%platform%"=="Win32" cmake -G "%CMAKE_GENERATOR_NAME%" -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" -DBIT:STRING=32 -DVERSION:STRING="${APPVEYOR_REPO_TAG_NAME}-build-${APPVEYOR_BUILD_NUMER}" ..
  - cmd: if "%platform%"=="x64" cmake -G "%CMAKE_GENERATOR_NAME%" -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" -DBIT:STRING=64 -DVERSION:STRING="%APPVEYOR_REPO_TAG_NAME%-build-%APPVEYOR_BUILD_NUMER%" ..
  - cmd: cmake --build . 
  - mv Debug/main.exe ../
  - cmd: dir
  - cd ..
  - cmd: dir
  - cmd: if "%platform%"=="Win32" mv main.exe main_x86.exe

test_script:
  - cmd: if "%platform%"=="Win32" main_x86.exe -version
  - cmd: if "%platform%"=="x64" main.exe -version

artifacts:
  - path: main.exe
    name: main
  - path: main_x86.exe
    name: main_x86

deploy:
  provider: Github
  auth_token:
    secure: 2ep5AcGb2Wl/vxhuoj8sYg/pTrcMmyChrOaS/BEytYqpPNB49lmkNVRrFpYB3KkL
  artifact: /main.*/
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true

  
