version: "{build}"

os: Visual Studio 2015

platform: Any CPU

environment:
  MSVC_DEFAULT_OPTIONS: ON
  BOOST_ROOT: C:\Libraries\boost_1_59_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_59_0\lib64-msvc-14.0

init:
  - cmd: cmake --version
  - cmd: msbuild /version

clone_folder: C:\projects\testgit

branches:
  except:
    - gh-pages

before_build:
  - mkdir build

build_script:
  - cd build
  - cmake -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" .
  - cmake --build . 

after_build:
  - cmd: main.exe -version


#build: off

  
test: off
