version: "{build}"

os: Visual Studio 2015

platform: 
  - x64
  

environment:
  MSVC_DEFAULT_OPTIONS: ON
  BOOST_ROOT: C:\Libraries\boost_1_59_0
  BOOST_LIBRARYDIR_32: C:\Libraries\boost_1_59_0\lib32-msvc-14.0
  BOOST_LIBRARYDIR_64: C:\Libraries\boost_1_59_0\lib64-msvc-14.0

init:
  - cmd: cmake --version
  - cmd: msbuild /version

clone_folder: C:\projects\testgit

branches:
  except:
    - gh-pages

before_build:
    - cmd: dir %BOOST_ROOT%\lib
      #- cmd: dir %BOOST_LIBRARYDIR_32%
    - cmd: dir C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32
    - cmd: set PATH=C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin;%PATH%
    - cmd: set CPLUS_INCLUDE_PATH=%BOOST_ROOT%;%BOOST_LIBRARYDIR_32%
    - cmd: mingw32-make.exe -
    - cmd: dir obj
    - cmd: g++ "-LD:C:\\Libraries\\boost_1_59_0\\lib64-msvc-14.0" "-LD:C:\\Libraries\\boost_1_59_0" -o main.exe obj/tyrant_optimize.o obj/read.o obj/sim.o obj/cards.o obj/xml.o obj/deck.o obj/tyrant.o

    - cmd: g++.exe -Wall -Werror -std=gnu++11 -Ofast -o obj/sim.o sim.cpp

build_script:
        # =VERSION

test_script:
  - cmd: if "%platform%"=="Win32" tuo_x86.exe -version
  - cmd: if "%platform%"=="x64" tuo.exe -version

artifacts:
  - path: tuo.exe
    name: tuo
  - path: tuo_x86.exe
    name: tuo_x86

deploy:
  provider: GitHub
  auth_token:
    secure: 2ep5AcGb2Wl/vxhuoj8sYg/pTrcMmyChrOaS/BEytYqpPNB49lmkNVRrFpYB3KkL
  artifact: /tuo.*/
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true

  
